###
# Questões ------------------------------------------------------------------------------------------------------------------------
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/questoes

###
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/questoes/67a29d02c052ab7ad7b31fe1

###
POST https:/fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/questoes
Content-Type: application/json

{
  "titulo": "Exemplo de Questão",
  "enunciado": "Texto do enunciado",
  "temaId": "12345",
  "dificuldade": 1,
  "alternativas": [
    { "texto": "Alternativa 1", "correto": false },
    { "texto": "Alternativa 2", "correto": true }
  ],
  "visivel": true
}

###
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/questoes/tema/{{temaId}}

###
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/questoes/dificuldade/{{nivel}}

###
DELETE https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/questoes/{{id}}

###
# Temas ------------------------------------------------------------------------------------------------------------------------
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/temas

###
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/temas/{{id}}

###
POST https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/temas
Content-Type: application/json

{
    "nome": "História do Brasil colônia",
    "descricao": "Questões relacionadas ao estudo do Brasil colônia.",
    "imagem":"https://static.todamateria.com.br/upload/56/d3/56d34472f00e8-brasil-colonia.jpg"
}

###
DELETE https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/temas/{{id}}

###
# Alternativas ------------------------------------------------------------------------------------------------------------------------
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/alternativas

###
GET https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/alternativas/{{id}}

###
POST https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/alternativas
Content-Type: application/json

{
  "texto": "Exemplo de Alternativa",
  "correto": true
}

###
PUT https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/alternativas/{{id}}
Content-Type: application/json

{
  "texto": "Texto atualizado",
  "correto": false
}

###
DELETE https://fidiquem-questoes-api-043ed1794ea9.herokuapp.com/api/v1/alternativas/{{id}}


